# ═══════════════════════════════════════════════════════════════════
#  TaskFlow — Terraform Infrastructure as Code
#  Simulates production infrastructure using Docker provider
#  (No cloud account needed — runs 100% locally)
# ═══════════════════════════════════════════════════════════════════

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "~> 3.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.4"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }

  # In production, use remote state:
  # backend "s3" {
  #   bucket = "taskflow-terraform-state"
  #   key    = "prod/terraform.tfstate"
  #   region = "us-east-1"
  # }
}

# ── Providers ───────────────────────────────────────────────────
provider "docker" {
  host = "unix:///var/run/docker.sock"
}

# ── Variables ───────────────────────────────────────────────────
variable "app_name" {
  description = "Application name"
  type        = string
  default     = "taskflow"
}

variable "environment" {
  description = "Deployment environment"
  type        = string
  default     = "production"
  validation {
    condition     = contains(["development", "staging", "production"], var.environment)
    error_message = "Environment must be development, staging, or production."
  }
}

variable "app_port" {
  description = "Port to expose the application on"
  type        = number
  default     = 5000
}

variable "replicas" {
  description = "Number of app container replicas"
  type        = number
  default     = 1
}

variable "image_tag" {
  description = "Docker image tag to deploy"
  type        = string
  default     = "latest"
}

# ── Random secret key ────────────────────────────────────────────
resource "random_password" "secret_key" {
  length           = 64
  special          = true
  override_special = "!@#$%^&*()-_=+"
}

# ── Docker Network ───────────────────────────────────────────────
resource "docker_network" "taskflow_net" {
  name   = "${var.app_name}-${var.environment}-network"
  driver = "bridge"

  labels {
    label = "managed-by"
    value = "terraform"
  }
  labels {
    label = "environment"
    value = var.environment
  }
}

# ── Docker Volume (persistent data) ─────────────────────────────
resource "docker_volume" "taskflow_data" {
  name = "${var.app_name}-${var.environment}-data"

  labels {
    label = "managed-by"
    value = "terraform"
  }
  labels {
    label = "app"
    value = var.app_name
  }
}

# ── Docker Image ─────────────────────────────────────────────────
resource "docker_image" "taskflow" {
  name         = "${var.app_name}:${var.image_tag}"
  keep_locally = true

  # In production, pull from registry:
  # name = "ghcr.io/youruser/taskflow:${var.image_tag}"
}

# ── App Container(s) ─────────────────────────────────────────────
resource "docker_container" "taskflow_app" {
  count = var.replicas

  name  = count.index == 0 ? "${var.app_name}-${var.environment}" : "${var.app_name}-${var.environment}-${count.index}"
  image = docker_image.taskflow.image_id

  restart = "unless-stopped"

  # Network
  networks_advanced {
    name = docker_network.taskflow_net.name
  }

  # Port mapping (only first replica gets the main port)
  dynamic "ports" {
    for_each = count.index == 0 ? [1] : []
    content {
      internal = 5000
      external = var.app_port
      protocol = "tcp"
    }
  }

  # Volume mount for SQLite persistence
  volumes {
    volume_name    = docker_volume.taskflow_data.name
    container_path = "/data"
  }

  # Environment variables
  env = [
    "SECRET_KEY=${random_password.secret_key.result}",
    "DATABASE_URL=sqlite:////data/taskflow.db",
    "ENVIRONMENT=${var.environment}",
  ]

  # Health check
  healthcheck {
    test         = ["CMD", "python", "-c",
                    "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"]
    interval     = "30s"
    timeout      = "10s"
    retries      = 3
    start_period = "15s"
  }

  # Resource limits
  memory      = 256  # MB
  memory_swap = 512

  labels {
    label = "managed-by"
    value = "terraform"
  }
  labels {
    label = "environment"
    value = var.environment
  }
  labels {
    label = "version"
    value = var.image_tag
  }
}

# ── Local: write .env file ────────────────────────────────────────
resource "local_file" "env_file" {
  filename        = "${path.module}/.env.terraform"
  file_permission = "0600"
  content         = <<-EOT
    # Generated by Terraform — DO NOT COMMIT
    # Environment: ${var.environment}
    SECRET_KEY=${random_password.secret_key.result}
    DATABASE_URL=sqlite:////data/taskflow.db
    APP_PORT=${var.app_port}
    ENVIRONMENT=${var.environment}
  EOT
}

# ── Outputs ──────────────────────────────────────────────────────
output "app_url" {
  description = "TaskFlow application URL"
  value       = "http://localhost:${var.app_port}"
}

output "container_names" {
  description = "Names of deployed containers"
  value       = docker_container.taskflow_app[*].name
}

output "network_name" {
  description = "Docker network name"
  value       = docker_network.taskflow_net.name
}

output "data_volume" {
  description = "Persistent data volume name"
  value       = docker_volume.taskflow_data.name
}

output "environment" {
  description = "Deployed environment"
  value       = var.environment
}

output "secret_key_length" {
  description = "Secret key length (not the key itself)"
  value       = length(random_password.secret_key.result)
  sensitive   = false
}
